openapi: 3.0.0
info:
  title: Jaljeera
  version: '0.1'
paths:
  /events:
    get:
      summary: List all events
      operationId: app.events.list
      responses:
        '200':
          description: Events list
          content:
    post:
      summary: Create a new event
      operationId: app.events.create
      responses:
        '200':
          description: Event created
  /events/{id}:
    get:
      summary: Get detailed data for an event
      operationId: app.events.get
      responses:
        '200':
          description: Event data (single)
    put:
      summary: Update event data
      operationId: app.events.update
      responses:
        '200':
          description: Event updated
    delete:
      summary: Delete a specific event
      operationId: app.events.delete
      responses:
        '200':
          description: Event deleted
  /collections:
    get:
      summary: List all collections
      operationId: app.collections.list
      responses:
    post:
      summary:
      operationId:
  /collections/{id}:
    get:
      summary: Get detailed data on a collection
      operationId: app.collections.get
    put:
      summary: Update collection data
      operationId: app.collections.update
    delete:
      summary: Delete a collection
      operationId: app.events.delete

# Decide between using Connexion's
# inbuilt security method to implement
# authentitcation or ignore and directly
# access the header using the connexion
# provided alias